// Generated by scripts/make-demo-tx.mjs, do not edit by hand.
// Spends utxo 0 of the default headless wallet. bodyEndHex is the hex offset
// right after the body, where the empty witness set (a0) sits.
var DEMO_TX = {
  unsignedHex: '84a300d901028182582067c3bcd4fc1b8cec56aa9501252a99ee5a8d5efb1a0b074cc1bb88d1ed582fa2000181825839009493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e32c728d3861e164cab28cb8f006448139c8f1740ffb8e7aa9e5232dc1a00958940021a00030d40a0f5f6',
  bodyEndHex: 232,
};
