// Writes examples/minimal-dapp/demo-tx.js: one unsigned transaction that
// spends utxo 0 of the default wallet (name chw, default mnemonic, 10 ADA)
// and pays 9.8 ADA back to the same address with a 0.2 ADA fee. The demo
// splices the wallet's witness set into it by hex offset because it has no
// CBOR library, a real dApp would use Evolution or Mesh for that step.
import { writeFileSync } from 'node:fs';
import { Tagged, bytesToHex, encode, hexToBytes, prepareWallet, syntheticOwnedUtxo } from '../dist/node/index.js';
import { bech32 } from '@scure/base';

const wallet = prepareWallet();
const address = Uint8Array.from(bech32.fromWords(bech32.decode(wallet.addresses.payment, false).words));
const utxo = syntheticOwnedUtxo(wallet.config.name, 0, address, 10_000_000n);

const body = new Map([
  [0n, new Tagged(258n, [[utxo.input.txId, utxo.input.index]])],
  [1n, [[address, 9_800_000n]]],
  [2n, 200_000n],
]);
const bodyHex = bytesToHex(encode(body));
const unsignedHex = bytesToHex(encode([body, new Map(), true, null]));
if (!unsignedHex.startsWith('84' + bodyHex + 'a0f5f6')) throw new Error('unexpected transaction layout');

const out = `// Generated by scripts/make-demo-tx.mjs, do not edit by hand.
// Spends utxo 0 of the default test wallet. bodyEndHex is the hex offset
// right after the body, where the empty witness set (a0) sits.
var DEMO_TX = {
  unsignedHex: '${unsignedHex}',
  bodyEndHex: ${2 + bodyHex.length},
};
`;
writeFileSync('examples/minimal-dapp/demo-tx.js', out);
console.log(`wrote demo-tx.js, ${hexToBytes(unsignedHex).length} bytes`);
