// Writes examples/minimal-dapp/demo-tx.js: one unsigned transaction that
// spends utxo 0 of the default wallet (name chw, default mnemonic, 10 ADA)
// and pays 9.8 ADA back to the same address with a 0.2 ADA fee. The demo
// splices the wallet's witness set into it by hex offset because it has no
// CBOR library, a real dApp would use Evolution or Mesh for that step.
import { writeFileSync } from 'node:fs';
import { bytesToHex, hexToBytes } from '../dist/node/core/bytes.js';
import { Tagged } from '../dist/node/core/cbor/decode.js';
import { encode } from '../dist/node/core/cbor/encode.js';
import { prepareWallet } from '../dist/node/index.js';
import { syntheticOwnedUtxo } from '../dist/node/page/install.js';
import { bech32 } from '@scure/base';

const wallet = prepareWallet();
const address = Uint8Array.from(bech32.fromWords(bech32.decode(wallet.addresses.payment, false).words));
const utxo = syntheticOwnedUtxo(wallet.config.name, 0, address, 10_000_000n);

const drepHash = hexToBytes(wallet.drepKeyHashHex);
const stakeHash = address.slice(29, 57);

function unsigned(extra) {
  const body = new Map([
    [0n, new Tagged(258n, [[utxo.input.txId, utxo.input.index]])],
    [1n, [[address, 9_800_000n]]],
    [2n, 200_000n],
    ...extra,
  ]);
  const bodyHex = bytesToHex(encode(body));
  const hex = bytesToHex(encode([body, new Map(), true, null]));
  if (!hex.startsWith('84' + bodyHex + 'a0f5f6')) throw new Error('unexpected transaction layout');
  return { unsignedHex: hex, bodyEndHex: 2 + bodyHex.length };
}

const commit = unsigned([]);
// A Yes vote by the wallet's own DRep on a fixed governance action id.
const vote = unsigned([[19n, new Map([[[2n, drepHash], new Map([[[new Uint8Array(32).fill(3), 0n], [1n, null]]])]])]]);
// delegation_to_drep (9): the wallet's stake credential delegates to its own DRep.
const deleg = unsigned([[4n, new Tagged(258n, [[9n, [0n, stakeHash], [0n, drepHash]]])]]);

const entry = (name, t) => `var ${name} = {\n  unsignedHex: '${t.unsignedHex}',\n  bodyEndHex: ${t.bodyEndHex},\n};\n`;
const out = `// Generated by scripts/make-demo-tx.mjs, do not edit by hand.
// Each transaction spends utxo 0 of the default test wallet. bodyEndHex is the
// hex offset right after the body, where the empty witness set (a0) sits.
${entry('DEMO_TX', commit)}${entry('DEMO_VOTE_TX', vote)}${entry('DEMO_DELEG_TX', deleg)}`;
writeFileSync('examples/minimal-dapp/demo-tx.js', out);
console.log('wrote demo-tx.js with DEMO_TX, DEMO_VOTE_TX and DEMO_DELEG_TX');
